_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  announcements_feed: 0
  automated_cron: 0
  backup_migrate: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  calendar_view: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  css_editor: 0
  csv_serialization: 0
  ctools: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  exif_orientation: 0
  facets: 0
  facets_exposed_filters: 0
  facets_range_widget: 0
  facets_searchbox_widget: 0
  feeds: 0
  feeds_log: 0
  feeds_tamper: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  honeypot: 0
  iframe: 0
  image: 0
  jquery_ui: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  language: 0
  link: 0
  linkit: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  protected_pages: 0
  rest: 0
  scanner: 0
  search_api: 0
  search_api_solr: 0
  search_api_solr_admin: 0
  search_api_sorts: 0
  serialization: 0
  shortcut: 0
  system: 0
  tamper: 0
  taxonomy: 0
  taxonomy_manager: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  video_embed_field: 0
  views_data_export: 0
  views_ui: 0
  webform: 0
  webform_node: 0
  webform_ui: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  stable9: 0
  artifactinfo: 0
profile: standard
