_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
protect_all_forms: false
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: true
element_name: url
time_limit: 5
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_feedback_form: false
  contact_message_personal_form: false
  node_article_form: false
  node_artifacts_form: false
  node_certificate_of_authenticity_form: false
  node_event_form: false
  node_learning_center_categories_form: false
  node_news_feed_form: false
  node_page_form: false
  node_puzzle_images_form: false
  node_puzzle_maker_form: false
  node_tlc_articles_form: false
  node_videos_for_learning_center_form: false
  node_webform_form: true
  comment_comment_form: false
