artifactinfo_custom.settings:
  type: config_object
  label: 'Artifact Info Custom settings'
  mapping:
    learning_page_background_image:
      type: integer
      label: 'Learning page background image'
      nullable: true
